config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:new, :create, :destroy]

  get "/" , to: "pictures#index"

  resources :users, only: [:new, :create, :edit, :show, :update, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, presence: true
  
  default_scope -> { order(created_at: :desc) }

  mount_uploader :image, ImageUploader

  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6}

  before_save { email.downcase! }
  has_secure_password

  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_check, only: [:new, :edit, :show, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    render :new if @picture.invalid?
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:content, :image, :image_cache)
    end

    def logged_in_check
      unless logged_in? then
        redirect_to new_session_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end      
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @favorite_pictures = @user.favorite_pictures
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>いんすたくろーん</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="container-fluid">
        <ul class="row">
        <% if logged_in? %>
          <li class="col-xs-3"><%= link_to "Home", "/" %></li>
          <li class="col-xs-3"><%= link_to "Post", new_picture_path %></li>
          <li class="col-xs-3"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="col-xs-3"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li class="col-xs-4"><%= link_to "Home", "/" %></li>        
          <li class="col-xs-4"> <%= link_to "Sign up", new_user_path %></li>
          <li class="col-xs-4"><%= link_to "Login", new_session_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="main">
      <div class="main-notice">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
      <div class="main-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="form">
  <%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

        <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <%= form.submit("post", :class => "btn btn-default") %>
    </div>
  <% end %>
</div>

app/views/pictures/confirm.html.erb
<div class="post-confirm">
  <h3>以下の内容で、Postする。</h3>
  <div class="post-confirm-confirm">
    <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image %>
      <%= form.hidden_field :image_cache %>

      <p>content:<%= @picture.content %></p>
      <p>image:<%= image_tag @picture.image %></p>
      <%= form.submit("post", :class => "btn btn-default") %>
    <% end %>
  </div>
  <div class="post-confirm-back">
    <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image %>
      <%= form.hidden_field :image_cache %>
      <%= form.submit("back", name: 'back', :class => "btn btn-default") %>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="editing-form">
  <h1>Editing Picture</h1>

  <%= render 'form', picture: @picture %>

  <%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/index.html.erb
<div class="posts-area">
  <% @pictures.each do |picture| %>
  <div class="post">
    <div class="post-user">
      <span class="post-user-image">
        
      </span>
      <span class="post-user-name">
        <a><%= picture.user.name %></a>
      </span>
    </div>
    <div class="post-picture">
      <%= image_tag picture.image %>
    </div>
    <div class="post-action">
      <%= link_to 'Show', picture %>
      <% if picture.user == current_user %>
      <%= link_to 'Edit', edit_picture_path(picture) %>
      <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <div class="post-text">
      <a><%= picture.content %></a>
    </div>
  </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<div class="new-form">
  <h1>New Picture</h1>

  <%= render 'form', picture: @picture %>

  <%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<div class="picture-show">
  <p>
    <strong>Content:</strong>
  </p>
  <div class="picture-show-content">
    <%= @picture.content %>
  </div>

  <p>
    <strong>Image:</strong>
  </p>
  <p>
    <%= image_tag @picture.image %>
  </p>

  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'un-Fav', favorite_path(id: @favorite.id), method: :delete %>
    <% else %>
      <%= link_to 'Fav', favorites_path(picture_id: @picture.id), method: :post %>
    <% end %>
  <% end %>
  <div>
    <%= link_to 'Edit', edit_picture_path(@picture) %> |
    <%= link_to 'Back', pictures_path %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit("Create my account", :class => "btn btn-default") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="profile-edit">
  <h1>Editing Profile</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', user_path %>
</div>

app/views/users/new.html.erb
<dev class="new-user">
  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>
</dev>

app/views/users/show.html.erb
<div class="profile-main">
  <div class="profile-user-name">
    <%= @user.name %>
  </div>
  <div class="profile-user-email">
    <%= @user.email %>
  </div>
  <div class="profile-edit-button">
    <%= link_to 'Edit', edit_user_path(@user) %>
  </div>
</div> 
<div class="profile-favorites">
  <h3>Favorites</h3>
    <% @favorite_pictures.each do |favorite_picture| %>
    <div class="post">
      <div class="post-user">
        <span class="post-user-image">
          
        </span>
        <span class="post-user-name">
          <a><%= favorite_picture.user.name %></a>
        </span>
      </div>
      <div class="post-picture">
        <%= image_tag favorite_picture.image %>
      </div>
      <div class="post-text">
        <a><%= favorite_picture.content %></a>
      </div>
    </div>
    <% end %>
</div>